### PR TITLE
Update settings images for Steampunk theme

### PR DESCRIPTION
**Pull request by smfontes**
Added missing images and removed text from existing images so it can use translated text. Updated Settings.xml to overlay translated text on top of images.

See example screen at https://forum.kodi.tv/showthread.php?tid=370550

### CODE REVIEW

**Comment by jingai** [comment]
Thank you for your submission!

I think, however, I would prefer no labels on the images at all, to match the other themes.  I am willing to entertain thoughts on this though.

**Comment by smfontes** [comment]
I like having the labels on the images that are not selected, so that you know what direction to move when you want to get to a particular setting. The images, though really interesting, aren't completely obvious as to what setting they correspond to.

**Comment by smfontes** [comment]
How about labels below he pictures, like [this](https://drive.google.com/file/d/10b7zgAFkC4n2zUyy8p10Pac3qIWHCcFI/view?usp=sharing) ?

**Comment by jingai** [comment]
Thank you, this has been merged.

**Pull request closed without merging**
