### PR TITLE
All the needed changes from Kodi 17 to 18

### PR DESCRIPTION
**Pull request by MacGyverr**
All the needed changes from Kodi 17 to 18, as well as some that must have been changed under 17 that were fully removed from Kodi 18.

### CODE REVIEW

**Comment by jingai** [comment]
VERY much appreciated man -- have been so busy lately I just haven't had the chance.

I'll look over this all in the next week or two.  Cheers!

**Comment by MacGyverr** [comment]
Sounds good.
Have a happy new year.

**Comment by jingai** [comment]
Remind me not to step away from this for 4 years ever again...

**Comment by jingai** [comment]
Almost all of this looks perfect in testing so far.  Again, I am _really_ sorry it took this long.

A few things stand out:

1. The 'wallpaper window' on the home screen should be only for wallpaper.  Different media has different aspect ratios.  For example, stretching a square album cover or a poster to 16:9 is wrong,
2. The square viewtypes are not supposed to be available to anything but Music and Pictures,
3. Low List viewtype for TV Show Seasons seems to lack the frame around the 2nd image.

I can fix all of these things.  Just letting you know what is holding it up.

I _really_ appreciate all of the extra effort you've made over the last few years to keep this alive.  Without you, I likely wouldn't even consider getting back into this.  Thanks!

**Comment by jingai** [comment]
Have merged everything (finally).  Thanks again @MacGyverr!

**Pull request closed without merging**
