### PR TITLE
Fixed missing icons, and made alpha Kodi 21 changes

### PR DESCRIPTION
**Pull request by MacGyverr**
Fixed missing flags and fixes for 20 and 21.
Added new Kodi 21 requirement changes where noted.
Disregard both "alt-flag" commits, one is a mistake the other undoes it.

### CODE REVIEW

**Comment by MacGyverr** [comment]
Disregard both "alt-flag" commits, one is a mistake the other undoes it.
I barely can use Github.

**Comment by jingai** [comment]
Very much appreciated, as usual.  I will merge when I get the chance.

**Comment by MacGyverr** [comment]
No problem, I do still use it after all.
I just wish some artistic type could come up with a Metropolis styled tri-paned popup, it's needed in a few places and I keep kludging something together, but those are all ugly. I have zero art talent and Dall-e and ChatGPT can't seem to do subtle, as you can see by this example I tried to coax out of it.

image

But you can get a decent set of design elements out of it if you try hard enough, still over the top though.
image


We still need to refactor the whole thing at some point to use this style of element usage:


	<include name="DefaultDialogButton">
		<param name="width">300</param>
		<param name="height">100</param>
		<param name="wrapmultiline">false</param>
		<param name="font">font25_title</param>
		<param name="onclick"></param>
		<param name="visible">true</param>
		<param name="enable">true</param>
		<definition>
			<control type="button" id="$PARAM[id]">
				<width>$PARAM[width]</width>
				<height>$PARAM[height]</height>
				<label>$PARAM[label]</label>
				<font>$PARAM[font]</font>
				<textoffsetx>20</textoffsetx>
				<onclick>$PARAM[onclick]</onclick>
				<wrapmultiline>$PARAM[wrapmultiline]</wrapmultiline>
				<align>center</align>
				<texturefocus border="40" colordiffuse="button_focus">buttons/dialogbutton-fo.png</texturefocus>
				<texturenofocus border="40">buttons/dialogbutton-nofo.png</texturenofocus>
				<visible>$PARAM[visible]</visible>
				<enable>$PARAM[enable]</enable>
			</control>
		</definition>
	</include>
	
	
And then call the one include everywhere like this:

				<include content="DefaultDialogButton">
					<param name="width" value="350" />
					<param name="id" value="18" />
					<param name="label" value="$LOCALIZE[186]" />
				</include>
				
It can be done with almost all elements at this point and reduces the number of lines everywhere, makes it look more uniform as well as making it easy to make changes everywhere from one place.
It's just a BUNCH of work and I might not live longer enough to finish it in my lifetime. :)

I'll look into it if I can find the time.

**Comment by jingai** [comment]
Aye, the biggest benefit to the skin at this point, IMHO, would be contributions from a real artist.  That I am not.  I took over the skin from Amra many years ago simply because I thought it was the best-looking and most sensibly-designed skin, and I wanted it to stick around.

There's loads to do in terms of refactoring and optimization, but at this point things generally work right, even if the code is a mess.  If an artist approached me, it would likely motivate me to think more about it again.  Until then though, I'm not unhappy with it (and neither is any member of my family), so I'm fine just keeping it up-to-date so it is available, which is completely thanks to you for the past few years, btw ;)

TBH, the download counts for the skin have never been insignificant relative to the others available -- with the exception of course of the Aeon variants -- so I'm a bit surprised no one has yet volunteered on the artwork front.

**Comment by jingai** [comment]
I will get to this once kodi 21 makes its way into Debian.

**Comment by MacGyverr** [comment]
I added a few more bug fixes a week or two ago at the request of some users, I didn't create a push for them though. I barely can get it synced with my local version and often have to rebase my stuff. I don't really know how to use github and struggle each time I have to use it. I also made a WIP release for 21 because people were having trouble installing the older version of it under 21.
One day I hope to be able to point one of the AIs at the code and have it fix it for us. :)

**Comment by jingai** [comment]
Looking at getting this merged in now.  I'm truly sorry it takes me so long these days.

**Comment by jingai** [comment]
Almost done.  I'll create another PR after this to give you a chance to check over since I cleaned up the commits.

@MacGyverr one question, though:  what is the reason for renaming the "Mosaic Purple" directory to "Mosaic-Purple"?  Did the space cause an issue in Kodi 21?

**Comment by jingai** [comment]
@MacGyverr in addon.xml, why remove the language, website, and email tags?  Are they no longer accepted?

**Comment by jingai** [comment]
It looks like DialogVideoVersion became DialogVideoManager at some point during development.  May just punt on it for now to at least get a release out.

**Comment by jingai** [comment]
#174 is going to be the first release unless you tell me that I've done something very wrong.  Going to close this PR, so continue discussion over there if there are any issues.

**Pull request closed without merging**
